with category_translations(slug, translations) as (
values
('entrantes', '{"es":{"name":"Entrantes","description":"Para compartir al centro de la mesa."},"ca":{"name":"Entrants","description":"Per compartir al centre de la taula."},"en":{"name":"Starters","description":"To share at the centre of the table."},"fr":{"name":"Entrées","description":"À partager au centre de la table."},"de":{"name":"Vorspeisen","description":"Zum Teilen in der Tischmitte."},"it":{"name":"Antipasti","description":"Da condividere al centro della tavola."},"pt":{"name":"Entradas","description":"Para partilhar no centro da mesa."},"nl":{"name":"Voorgerechten","description":"Om samen aan tafel te delen."},"ru":{"name":"Закуски","description":"Для общей подачи в центре стола."}}'::jsonb),
('antipasti', '{"es":{"name":"Antipasti","description":"Bocados italianos con producto cuidado."},"ca":{"name":"Antipasti","description":"Mossegades italianes amb producte cuidat."},"en":{"name":"Antipasti","description":"Italian bites made with carefully selected ingredients."},"fr":{"name":"Antipasti","description":"Bouchées italiennes avec des produits soignés."},"de":{"name":"Antipasti","description":"Italienische Kleinigkeiten mit sorgfältig ausgewählten Zutaten."},"it":{"name":"Antipasti","description":"Bocconi italiani con ingredienti curati."},"pt":{"name":"Antipasti","description":"Petiscos italianos com produto cuidado."},"nl":{"name":"Antipasti","description":"Italiaanse hapjes met zorgvuldig gekozen producten."},"ru":{"name":"Антипасти","description":"Итальянские закуски из тщательно подобранных продуктов."}}'::jsonb),
('ensaladas', '{"es":{"name":"Ensaladas","description":"Frescas, completas y mediterráneas."},"ca":{"name":"Amanides","description":"Fresques, completes i mediterrànies."},"en":{"name":"Salads","description":"Fresh, complete and Mediterranean."},"fr":{"name":"Salades","description":"Fraîches, complètes et méditerranéennes."},"de":{"name":"Salate","description":"Frisch, vollwertig und mediterran."},"it":{"name":"Insalate","description":"Fresche, complete e mediterranee."},"pt":{"name":"Saladas","description":"Frescas, completas e mediterrânicas."},"nl":{"name":"Salades","description":"Fris, compleet en mediterraan."},"ru":{"name":"Салаты","description":"Свежие, сытные и средиземноморские."}}'::jsonb),
('carnes-a-la-brasa', '{"es":{"name":"Carnes a la brasa","description":"Cortes de carne y parrilla."},"ca":{"name":"Carns a la brasa","description":"Talls de carn i graella."},"en":{"name":"Grilled meats","description":"Cuts of meat from the grill."},"fr":{"name":"Viandes grillées","description":"Morceaux de viande et grillades."},"de":{"name":"Grillfleisch","description":"Fleischstücke vom Grill."},"it":{"name":"Carni alla brace","description":"Tagli di carne alla griglia."},"pt":{"name":"Carnes grelhadas","description":"Cortes de carne grelhados."},"nl":{"name":"Gegrild vlees","description":"Vlees van de grill."},"ru":{"name":"Мясо на гриле","description":"Мясные отрубы с гриля."}}'::jsonb),
('hamburguesas', '{"es":{"name":"Hamburguesas","description":"Burgers con patatas y salsas."},"ca":{"name":"Hamburgueses","description":"Burgers amb patates i salses."},"en":{"name":"Burgers","description":"Burgers with fries and sauces."},"fr":{"name":"Burgers","description":"Burgers avec frites et sauces."},"de":{"name":"Burger","description":"Burger mit Pommes und Saucen."},"it":{"name":"Hamburger","description":"Burger con patatine e salse."},"pt":{"name":"Hambúrgueres","description":"Burgers com batatas e molhos."},"nl":{"name":"Burgers","description":"Burgers met friet en sauzen."},"ru":{"name":"Бургеры","description":"Бургеры с картофелем и соусами."}}'::jsonb),
('pescado', '{"es":{"name":"Pescado","description":"Pescados y mariscos a la plancha."},"ca":{"name":"Peix","description":"Peixos i mariscos a la planxa."},"en":{"name":"Fish","description":"Fish and seafood from the grill."},"fr":{"name":"Poisson","description":"Poissons et fruits de mer grillés."},"de":{"name":"Fisch","description":"Fisch und Meeresfrüchte vom Grill."},"it":{"name":"Pesce","description":"Pesce e frutti di mare alla piastra."},"pt":{"name":"Peixe","description":"Peixes e mariscos grelhados."},"nl":{"name":"Vis","description":"Vis en zeevruchten van de grill."},"ru":{"name":"Рыба","description":"Рыба и морепродукты на гриле."}}'::jsonb),
('arroces-y-risottos', '{"es":{"name":"Arroces y risottos","description":"Arroces para compartir y risottos cremosos."},"ca":{"name":"Arrossos i risottos","description":"Arrossos per compartir i risottos cremosos."},"en":{"name":"Rice dishes and risottos","description":"Rice dishes to share and creamy risottos."},"fr":{"name":"Riz et risottos","description":"Riz à partager et risottos crémeux."},"de":{"name":"Reisgerichte und Risottos","description":"Reisgerichte zum Teilen und cremige Risottos."},"it":{"name":"Risi e risotti","description":"Risi da condividere e risotti cremosi."},"pt":{"name":"Arrozes e risottos","description":"Arrozes para partilhar e risottos cremosos."},"nl":{"name":"Rijstgerechten en risotto’s","description":"Rijstgerechten om te delen en romige risotto’s."},"ru":{"name":"Рисовые блюда и ризотто","description":"Рисовые блюда для компании и кремовые ризотто."}}'::jsonb),
('menu-de-ninos', '{"es":{"name":"Menú de niños","description":"Para menores de 12 años. Bebida incluida."},"ca":{"name":"Menú infantil","description":"Per a menors de 12 anys. Beguda inclosa."},"en":{"name":"Kids menu","description":"For children under 12. Drink included."},"fr":{"name":"Menu enfants","description":"Pour les moins de 12 ans. Boisson incluse."},"de":{"name":"Kindermenü","description":"Für Kinder unter 12 Jahren. Getränk inklusive."},"it":{"name":"Menu bambini","description":"Per bambini sotto i 12 anni. Bevanda inclusa."},"pt":{"name":"Menu infantil","description":"Para menores de 12 anos. Bebida incluída."},"nl":{"name":"Kindermenu","description":"Voor kinderen onder 12 jaar. Drankje inbegrepen."},"ru":{"name":"Детское меню","description":"Для детей до 12 лет. Напиток включен."}}'::jsonb),
('pizzas-artesanales', '{"es":{"name":"Pizzas artesanales","description":"Masa artesanal y horno caliente."},"ca":{"name":"Pizzes artesanes","description":"Massa artesana i forn calent."},"en":{"name":"Artisan pizzas","description":"Handmade dough and a hot oven."},"fr":{"name":"Pizzas artisanales","description":"Pâte artisanale et four chaud."},"de":{"name":"Hausgemachte Pizzen","description":"Handgemachter Teig und heißer Ofen."},"it":{"name":"Pizze artigianali","description":"Impasto artigianale e forno caldo."},"pt":{"name":"Pizzas artesanais","description":"Massa artesanal e forno quente."},"nl":{"name":"Ambachtelijke pizza’s","description":"Handgemaakt deeg en een hete oven."},"ru":{"name":"Авторская пицца","description":"Домашнее тесто и горячая печь."}}'::jsonb),
('calzones-y-pinsas-artesanales', '{"es":{"name":"Calzones y pinsas artesanales","description":"Especialidades artesanas al estilo italiano."},"ca":{"name":"Calzones i pinses artesanes","description":"Especialitats artesanes a l’estil italià."},"en":{"name":"Artisan calzones and pinsas","description":"Italian-style artisan specialities."},"fr":{"name":"Calzones et pinsas artisanales","description":"Spécialités artisanales à l’italienne."},"de":{"name":"Hausgemachte Calzones und Pinsas","description":"Italienische handwerkliche Spezialitäten."},"it":{"name":"Calzoni e pinse artigianali","description":"Specialità artigianali in stile italiano."},"pt":{"name":"Calzones e pinsas artesanais","description":"Especialidades artesanais ao estilo italiano."},"nl":{"name":"Ambachtelijke calzones en pinsa’s","description":"Italiaanse ambachtelijke specialiteiten."},"ru":{"name":"Кальцоне и пинса","description":"Итальянские авторские блюда."}}'::jsonb),
('pasta', '{"es":{"name":"Pasta","description":"Base editable de pastas clásicas."},"ca":{"name":"Pasta","description":"Base editable de pastes clàssiques."},"en":{"name":"Pasta","description":"Classic pasta dishes."},"fr":{"name":"Pâtes","description":"Pâtes classiques."},"de":{"name":"Pasta","description":"Klassische Pastagerichte."},"it":{"name":"Pasta","description":"Piatti di pasta classici."},"pt":{"name":"Pasta","description":"Pratos clássicos de pasta."},"nl":{"name":"Pasta","description":"Klassieke pastagerechten."},"ru":{"name":"Паста","description":"Классическая паста."}}'::jsonb)
)
insert into content_translations (entity_type, entity_id, field_name, language, translated_text, source_text_hash)
select 'CATEGORY', c.id, field_values.field_name, language_values.language, field_values.field_value, 'manual-category-v12'
from category_translations
join categories c on c.slug = category_translations.slug
cross join lateral jsonb_each(category_translations.translations) as language_values(language, data)
cross join lateral (values
    ('name', language_values.data ->> 'name'),
    ('description', language_values.data ->> 'description')
) as field_values(field_name, field_value)
on conflict (entity_type, entity_id, field_name, language)
do update set
    translated_text = excluded.translated_text,
    source_text_hash = excluded.source_text_hash,
    updated_at = now();

update categories c
set
    name = name_translation.translated_text,
    description = description_translation.translated_text
from content_translations name_translation
join content_translations description_translation
    on description_translation.entity_type = name_translation.entity_type
    and description_translation.entity_id = name_translation.entity_id
    and description_translation.language = name_translation.language
    and description_translation.field_name = 'description'
where name_translation.entity_type = 'CATEGORY'
  and name_translation.field_name = 'name'
  and name_translation.language = 'es'
  and name_translation.source_text_hash = 'manual-category-v12'
  and description_translation.source_text_hash = 'manual-category-v12'
  and c.id = name_translation.entity_id;
